import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'Doc-AI-Agent-development',
  tagline: 'Documentation for AI Agent development',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  // GitHub Pages serves an organization site at https://<org>.github.io/.
  url: 'https://doc-ai-agent-development.github.io',
  baseUrl: '/',

  organizationName: 'Doc-AI-Agent-development',
  projectName: 'Doc-AI-Agent-development.github.io',

  onBrokenLinks: 'warn',

  // .md = plain markdown (no JSX in `{...}` expressions); .mdx = MDX.
  // Docusaurus v4's default is 'mdx' for both extensions, which makes
  // raw markdown that contains `{...}` blow up the build. 'detect' keeps
  // plain .md files safe so you can drop notes in without escaping.
  markdown: {
    format: 'detect',
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          // Sidebar is autogenerated from the docs/ folder tree, so a new
          // .md file shows up in the nav automatically — no manual edits.
          sidebarPath: './sidebars.ts',
          editUrl:
            'https://github.com/Doc-AI-Agent-development/Doc-AI-Agent-development.github.io/tree/main/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'Doc-AI-Agent-development',
      logo: {
        alt: 'Doc-AI-Agent-development',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'tutorialSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/Doc-AI-Agent-development',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {label: 'Introduction', to: '/docs/intro'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'GitHub', href: 'https://github.com/Doc-AI-Agent-development'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Doc-AI-Agent-development. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
