import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Autogenerated sidebar.
 *
 * The sidebar is built from the folder tree under docs/. Drop a new
 * `.md` file into docs/ (or a subfolder) and it appears in the nav
 * automatically — no edits here required.
 *
 * To control ordering or labels, add front matter to a doc
 * (`sidebar_position: 1`, `sidebar_label: 'My label'`) or a
 * `_category_.json` to a folder. See:
 * https://docusaurus.io/docs/sidebar/autogenerated
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
